vich_uploader:
    db_driver: orm # Utilisez ORM si vous utilisez Doctrine ORM

    metadata:
        type: attribute

    mappings:
        # Configuration spécifique à votre entité
        your_entity_name:
            uri_prefix: /uploads/
            upload_destination: '%kernel.project_dir%/public/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer